<a href="https://colab.research.google.com/github/Mat9408/Analise_Voos_India/blob/main/Trabalho_Aula_4_Parte_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Atividade de Ciência de Dados - Matheus da Cunha Alves - 2022101251

O dataset selecionado contém registros de viagens aéreas entre cidades da Índia.

Dataset escolhido: https://www.kaggle.com/datasets/rohitgrewal/airlines-flights-data

In [ ]:
import pandas as pd

In [ ]:
base = pd.read_csv('airlines_flights_data.csv', sep=',')

In [ ]:
base.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [ ]:
base.tail()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
base.shape

(300153, 12)

In [ ]:
display(base)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
base.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
dtype: object

In [ ]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [ ]:
base.isnull().sum()

index               0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [ ]:
#Mostrando a média de preço das passagens aéreas.
media_preco = base['price'].mean()
print(media_preco)

20889.660523133203

In [ ]:
base.count()

index               300153
airline             300153
flight              300153
source_city         300153
departure_time      300153
stops               300153
arrival_time        300153
destination_city    300153
class               300153
duration            300153
days_left           300153
price               300153
dtype: int64

In [ ]:
#Média de duração de vôo
base['duration'].mean()

np.float64(12.221020812718846)

In [ ]:
#Mediana de duração do tempo de vôo
base['duration'].median()

11.25

In [ ]:
#Desvio Padrão do tempo de vôo
base['duration'].std()

7.191997238118316

In [ ]:
#Resumo estatístico utilizando o describe na coluna "Price"
base['price'].describe()

count    300153.000000
mean      20889.660523
std       22697.767366
min        1105.000000
25%        4783.000000
50%        7425.000000
75%       42521.000000
max      123071.000000
Name: price, dtype: float64

In [ ]:
#Selecionando uma coluna do dataset
base['airline']

0         SpiceJet
1         SpiceJet
2          AirAsia
3          Vistara
4          Vistara
            ...
300148     Vistara
300149     Vistara
300150     Vistara
300151     Vistara
300152     Vistara
Name: airline, Length: 300153, dtype: object

In [ ]:
#Selecionando coluna com ponto
base.source_city

0           Delhi
1           Delhi
2           Delhi
3           Delhi
4           Delhi
           ...
300148    Chennai
300149    Chennai
300150    Chennai
300151    Chennai
300152    Chennai
Name: source_city, Length: 300153, dtype: object

In [ ]:
base.source_city.value_counts()

source_city
Delhi        61343
Mumbai       60896
Bangalore    52061
Kolkata      46347
Hyderabad    40806
Chennai      38700
Name: count, dtype: int64

In [ ]:
#Selecionando um conjunto de colunas
base[['airline','flight','class','price']]

         airline   flight     class  price
0       SpiceJet  SG-8709   Economy   5953
1       SpiceJet  SG-8157   Economy   5953
2        AirAsia   I5-764   Economy   5956
3        Vistara   UK-995   Economy   5955
4        Vistara   UK-963   Economy   5955
...          ...      ...       ...    ...
300148   Vistara   UK-822  Business  69265
300149   Vistara   UK-826  Business  77105
300150   Vistara   UK-832  Business  79099
300151   Vistara   UK-828  Business  81585
300152   Vistara   UK-822  Business  81585

[300153 rows x 4 columns]

In [ ]:
#Verificando as passagens que custam mais de 100.000
base[base.price > 100000]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
215858,215858,Vistara,UK-809,Delhi,Evening,two_or_more,Evening,Kolkata,Business,21.08,1,114434
215859,215859,Vistara,UK-809,Delhi,Evening,two_or_more,Evening,Kolkata,Business,21.08,1,116562
216025,216025,Vistara,UK-817,Delhi,Evening,two_or_more,Morning,Kolkata,Business,17.58,4,100395
216095,216095,Vistara,UK-963,Delhi,Morning,one,Evening,Kolkata,Business,8.00,5,101369
216096,216096,Vistara,UK-811,Delhi,Early_Morning,two_or_more,Evening,Kolkata,Business,10.92,5,117307
...,...,...,...,...,...,...,...,...,...,...,...,...
293474,293474,Vistara,UK-836,Chennai,Morning,one,Night,Bangalore,Business,9.67,3,107597
296001,296001,Vistara,UK-838,Chennai,Night,one,Morning,Kolkata,Business,11.50,3,102832
296081,296081,Vistara,UK-832,Chennai,Early_Morning,one,Night,Kolkata,Business,15.83,5,102384
296170,296170,Vistara,UK-838,Chennai,Night,one,Morning,Kolkata,Business,11.50,7,104624
296404,296404,Vistara,UK-838,Chennai,Night,one,Evening,Kolkata,Business,21.00,12,102384

In [ ]:
#Verificando se houve algum vôo com menos de 1h de duração
base[base.duration < 1.00]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
115662,115662,AirAsia,I5-5204,Bangalore,Early_Morning,zero,Early_Morning,Chennai,Economy,0.92,3,3499
115869,115869,Indigo,6E-357,Bangalore,Night,zero,Night,Chennai,Economy,0.83,6,3498
115943,115943,Indigo,6E-357,Bangalore,Night,zero,Night,Chennai,Economy,0.83,7,3498
116010,116010,Indigo,6E-357,Bangalore,Night,zero,Night,Chennai,Economy,0.83,8,3498
116081,116081,Indigo,6E-357,Bangalore,Night,zero,Night,Chennai,Economy,0.83,9,3498
...,...,...,...,...,...,...,...,...,...,...,...,...
197713,197713,Indigo,6E-477,Chennai,Early_Morning,zero,Morning,Bangalore,Economy,0.83,49,1443
197714,197714,Indigo,6E-605,Chennai,Afternoon,zero,Afternoon,Bangalore,Economy,0.92,49,1443
197715,197715,Indigo,6E-6113,Chennai,Afternoon,zero,Afternoon,Bangalore,Economy,0.92,49,1443
197716,197716,Indigo,6E-847,Chennai,Evening,zero,Evening,Bangalore,Economy,0.92,49,1443
197724,197724,Indigo,6E-6137,Chennai,Morning,zero,Morning,Bangalore,Economy,0.83,49,1549

In [ ]:
#Verificando se houve vôos noturnos para Dheli
base[(base.departure_time == 'Night') & (base.destination_city == 'Delhi')].head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
43033,43033,Air_India,AI-867,Mumbai,Night,zero,Night,Delhi,Economy,2.25,1,5943
43039,43039,SpiceJet,SG-8710,Mumbai,Night,zero,Night,Delhi,Economy,2.17,1,6048
43059,43059,Vistara,UK-988,Mumbai,Night,zero,Night,Delhi,Economy,2.08,1,12768
43112,43112,SpiceJet,SG-8710,Mumbai,Night,zero,Night,Delhi,Economy,2.00,2,5943
43114,43114,Vistara,UK-988,Mumbai,Night,zero,Night,Delhi,Economy,2.08,2,5943

In [ ]:
#Utilizando o iloc para realizar o filtro acima
base.loc[(base.departure_time == "Night") & (base.destination_city == "Delhi")].head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
43033,43033,Air_India,AI-867,Mumbai,Night,zero,Night,Delhi,Economy,2.25,1,5943
43039,43039,SpiceJet,SG-8710,Mumbai,Night,zero,Night,Delhi,Economy,2.17,1,6048
43059,43059,Vistara,UK-988,Mumbai,Night,zero,Night,Delhi,Economy,2.08,1,12768
43112,43112,SpiceJet,SG-8710,Mumbai,Night,zero,Night,Delhi,Economy,2.00,2,5943
43114,43114,Vistara,UK-988,Mumbai,Night,zero,Night,Delhi,Economy,2.08,2,5943

In [ ]:
#Utilizando argumentos lógicos
base.loc[(base.departure_time == "Night") | (base.destination_city == 'Delhi'), ['flight']].head()

    flight
40  AI-504
44  AI-479
50  AI-540
58  6E-369
69  UK-871

In [ ]:
#Busca apenas por colunas linhas específicas
base.iloc[3:7, 1:3]

   airline  flight
3  Vistara  UK-995
4  Vistara  UK-963
5  Vistara  UK-945
6  Vistara  UK-927